services:
  machine-service:
    image: openjdk:22-jdk-oracle
    container_name: machineImage
    ports:
      - "${SERVICE_PORT1}:8080"
      - "${SERVICE_PORT2}:8000"
    env_file:
      - .env
    depends_on:
      - machine-db
    networks:
      - iot-net
    volumes:
      - ./build/libs/MachineService-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  machine-db:
    image: mongo:latest
    container_name: machineDB
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_machine:/etc/mongo
      - mongo_machine_data:/data/db
      - mongo_machine_config:/data/configdb
    networks:
      - iot-net

networks:
  iot-net:
    external: true

volumes:
  mongo_machine:
  mongo_machine_data:
  mongo_machine_config:
