services:
  userman-service:
    image: openjdk:22-jdk-oracle
    container_name: usermanImage
    ports:
      - "${SERVICE_PORT1}:8080"
      - "${SERVICE_PORT2}:8000"
    depends_on:
      - userman-db
    env_file:
      - .env
    networks:
      - iot-net
    volumes:
      - ./build/libs/UserManagementService-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  userman-db:
    image: mongo:latest
    container_name: usermanDB
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_userman:/etc/mongo
      - mongo_userman_data:/data/db
      - mongo_userman_config:/data/configdb
    networks:
      - iot-net

networks:
  iot-net:
    external: true

volumes:
  mongo_userman:
  mongo_userman_data:
  mongo_userman_config:
