CREATE TABLE IF NOT EXISTS machine_vibration (
    id STRING PRIMARY KEY DEFAULT gen_random_text_uuid(),
    machine_name TEXT,
    mean_x REAL,
    mean_y REAL,
    mean_z REAL,
    rms_x REAL,
    rms_y REAL,
    rms_z REAL,
    min_x REAL,
    min_y REAL,
    min_z REAL,
    max_x REAL,
    max_y REAL,
    max_z REAL,
    std_x REAL,
    std_y REAL,
    std_z REAL,
    kurtosis_x REAL,
    kurtosis_y REAL,
    kurtosis_z REAL,
    skewness_x REAL,
    skewness_y REAL,
    skewness_z REAL,
    peak_to_peak_x REAL,
    peak_to_peak_y REAL,
    peak_to_peak_z REAL,
    energy_x REAL,
    energy_y REAL,
    energy_z REAL,
    prediction BOOLEAN,
    timestamp TIMESTAMP WITH TIME ZONE
);